import type { CatalogItem } from './types';

function p(path: string): string {
  return path.split('/').map(encodeURIComponent).join('/');
}
function real(path: string, alt: string) {
  return { url: p(`/img/PROJECT BASED/${path}`), alt };
}
function ai(path: string, alt: string) {
  return { url: p(`/img/AI BASED/${path}`), alt };
}

export const interiorElements: CatalogItem[] = [
  {
    slug: 'kitchen',
    title: 'Kitchen',
    eyebrow: 'Interior Element',
    heroImage: real('MODULAR KITCHEN/Rakesh ji living A01_View070000.webp', 'Modular kitchen by Luxora, Jaipur'),
    description: 'The working heart of the home — planned around your cooking habits first, then built with German-grade hardware and countertops chosen for daily use.',
    highlights: ['Efficient working-triangle layouts', 'German-grade soft-close hardware', 'Durable countertops and backsplashes', 'Concealed appliance garages'],
    gallery: [
      real('MODULAR KITCHEN/Krish ji C01_View010000.webp', 'Modular kitchen, Krish Residence, Jaipur'),
      real('MODULAR KITCHEN/Rishabh ji kitchen E01.webp', 'Modular kitchen, Rishabh Residence, Jaipur'),
      real('MODULAR KITCHEN/DD khandelwal kitchen A01.webp', 'Modular kitchen, Jaipur'),
      real('MODULAR KITCHEN/Ajit ji khichar A07.webp', 'Modular kitchen interior, Jaipur'),
    ],
    gallerySlug: 'kitchen',
    serviceSlug: 'modular-kitchen-design',
    relatedPortfolioSlugs: ['rakesh-ji-residence', 'rishabh-ji-residence'],
  },
  {
    slug: 'wardrobes',
    title: 'Wardrobes',
    eyebrow: 'Interior Element',
    heroImage: real('WARDROBE DESIGN/Rishabh ji Master Bedroom A04.webp', 'Custom wardrobe by Luxora, Jaipur'),
    description: 'Storage planned by what you actually own, then built to disappear into the architecture of the room rather than sit as furniture against a wall.',
    highlights: ['Interior layouts planned by your wardrobe count', 'Soft-close hardware and internal LED lighting', 'Sliding, openable or walk-in configurations', 'Finishes matched to your room'],
    gallery: [
      real('WARDROBE DESIGN/Krish ji Dressing A01_View010000.webp', 'Wardrobe, Krish Residence, Jaipur'),
      real('WARDROBE DESIGN/GAUTMA JI M. BEDROOM DRESSING A01.webp', 'Wardrobe and dressing area, Jaipur'),
      real('WARDROBE DESIGN/Vizora House F.F. A01_View180000_View01000.webp', 'Wardrobe wall, Vizora House, Jaipur'),
      real('WARDROBE DESIGN/Rishabh ji Doughter bedroom dressing A01.webp', 'Dressing area, Rishabh Residence, Jaipur'),
    ],
    gallerySlug: 'wardrobes',
    serviceSlug: 'wardrobe-design',
    relatedPortfolioSlugs: ['krish-ji-residence', 'rishabh-ji-residence'],
  },
  {
    slug: 'living',
    title: 'Living',
    eyebrow: 'Interior Element',
    heroImage: real('LIVING ROOM DESIGN/Vizora House G.F. A01_View040000.webp', 'Living room by Luxora, Jaipur'),
    description: 'The room your home is judged by first — planned as one continuous sightline with dining and entrance, in a single considered material language.',
    highlights: ['Furniture layouts built for daily life and guests', 'Custom media walls and seating', 'One material language carried through the space', 'Layered ambient and task lighting'],
    gallery: [
      real('LIVING ROOM DESIGN/Krish ji S.F. A01_View130000.webp', 'Living room, Krish Residence, Jaipur'),
      real('LIVING ROOM DESIGN/Karamveer ji G.F. A01_View080000.webp', 'Living room, Karamveer Residence, Jaipur'),
      real('LIVING ROOM DESIGN/Paritosh ji Living A01_View040000.webp', 'Living room, Paritosh Residence, Jaipur'),
      ai('LIVING BEDROOM DESIGNS/lr3.webp', 'Living room design concept, Jaipur'),
    ],
    gallerySlug: 'living-room',
    serviceSlug: 'living-room-interior-design',
    relatedPortfolioSlugs: ['vizora-house', 'krish-ji-residence'],
  },
  {
    slug: 'bedroom',
    title: 'Bedroom',
    eyebrow: 'Interior Element',
    heroImage: real('MASTER BEDROOM DESIGN/Krish ji Bedroom A02.webp', 'Master bedroom by Luxora, Jaipur'),
    description: 'A quiet, considered retreat — built around rest, with dedicated lighting circuits for reading, dressing and sleep.',
    highlights: ['Layered lighting for reading, dressing and sleep', 'Integrated wardrobe walls', 'Soft, restrained material palettes', 'Ensuite bathroom coordination'],
    gallery: [
      real('MASTER BEDROOM DESIGN/Rishabh ji final render 01.webp', 'Master bedroom, Rishabh Residence, Jaipur'),
      real('MASTER BEDROOM DESIGN/Vizora House G.F. A01_View070000.webp', 'Master bedroom, Vizora House, Jaipur'),
      real('KIDS BEDROOM DESIGN/Krish ji Girls bedroom A02.webp', "Kids' bedroom, Krish Residence, Jaipur"),
      ai('MASTER BEDROOM DESIGNS/mb2.webp', 'Master bedroom design concept, Jaipur'),
    ],
    gallerySlug: 'bedroom',
    serviceSlug: 'bedroom-interior-design',
    relatedPortfolioSlugs: ['rishabh-ji-residence', 'vizora-house'],
  },
  {
    slug: 'dining',
    title: 'Dining',
    eyebrow: 'Interior Element',
    heroImage: real('DINING ROOM DESIGN/Rishabh ji  final 20-5-2025 A01_View120078.webp', 'Dining room by Luxora, Jaipur'),
    description: 'Planned as part of the living-and-kitchen flow, not a room on its own — so entertaining never feels disconnected from the rest of the home.',
    highlights: ['Seating planned around your household size', 'Coordinated with adjoining kitchen and living areas', 'Statement lighting above the table', 'Durable, easy-to-maintain finishes'],
    gallery: [
      real('DINING ROOM DESIGN/Karamveer ji G.F. A01_View090000.webp', 'Dining area, Karamveer Residence, Jaipur'),
      real('DINING ROOM DESIGN/krish ji entrance+kitchen+dining area A01_View040100.webp', 'Dining area, Krish Residence, Jaipur'),
      real('DINING ROOM DESIGN/Paritosh ji Living A01_View080000.webp', 'Dining area, Paritosh Residence, Jaipur'),
      real('DINING ROOM DESIGN/Mohit ji Living and dining B01_View050000.webp', 'Dining area, Mohit Residence, Jaipur'),
    ],
    gallerySlug: 'living-room',
    serviceSlug: 'full-home-interior-design',
    relatedPortfolioSlugs: ['krish-ji-residence', 'karamveer-ji-residence'],
  },
  {
    slug: 'office',
    title: 'Office',
    eyebrow: 'Interior Element',
    heroImage: real('OFFICES BY LUXORA/ASHRIT JI B_View030000.webp', 'Office interior by Luxora, Jaipur'),
    description: 'Workspaces built for identity and performance — reception, open desking and private cabins under one brand-driven material language.',
    highlights: ['Reception designed to make the right first impression', 'Zoned open desking for focus and collaboration', 'Acoustic-treated meeting rooms', 'A single accent material carried throughout'],
    gallery: [
      real('OFFICES BY LUXORA/ASHRIT JI B_View010000.webp', 'Reception, Ashrit Corporate Studio, Jaipur'),
      real('OFFICES BY LUXORA/Bansal ji office A01_View010000.webp', 'Office interior, Bansal Office Studio, Jaipur'),
      real('OFFICES BY LUXORA/Hariom ji office C01_View010000.webp', 'Office reception, Hariom Corporate Office, Jaipur'),
      ai('HOME OFFICE/ofc2.webp', 'Home office design concept, Jaipur'),
    ],
    gallerySlug: 'office',
    serviceSlug: 'commercial-office-interior-design',
    relatedPortfolioSlugs: ['ashrit-corporate-studio', 'bansal-ji-office'],
  },
  {
    slug: 'bathroom',
    title: 'Bathroom',
    eyebrow: 'Interior Element',
    heroImage: real('BATHROOM DESIGN/Krish ji Dressing A01_View070000.webp', 'Bathroom by Luxora, Jaipur'),
    description: 'Finished with the same attention as the more visible rooms — water-resistant materials that still read as considered design, not purely functional fittings.',
    highlights: ['Water-resistant, easy-to-maintain finishes', 'Coordinated with adjoining bedroom material language', 'Ventilation and lighting planned together', 'Fittings chosen for long-term durability'],
    gallery: [
      real('BATHROOM DESIGN/Rishabh ji Master Bedroom A05.webp', 'Ensuite bathroom, Rishabh Residence, Jaipur'),
      real('BATHROOM DESIGN/Balram ji Bathroom B01_View010000.webp', 'Bathroom, Balram Residence, Jaipur'),
      real('BATHROOM DESIGN/krish ji f.f. bathroom&dressing A03.webp', 'Bathroom, Krish Residence, Jaipur'),
      real('BATHROOM DESIGN/Rishabh ji Doughter bedroom bathroom B01.webp', "Daughter's bathroom, Rishabh Residence, Jaipur"),
    ],
    gallerySlug: 'bedroom',
    serviceSlug: 'bedroom-interior-design',
    relatedPortfolioSlugs: ['rishabh-ji-residence', 'balram-ji-residence'],
  },
  {
    slug: 'lighting',
    title: 'Lighting',
    eyebrow: 'Interior Element',
    heroImage: ai('FALSE CIELING DESIGN/fc5.webp', 'Layered lighting design concept, Jaipur'),
    description: 'Lighting planned in layers — ambient, task and accent — and coordinated with the false ceiling and automation system rather than added as an afterthought.',
    highlights: ['Ambient, task and accent layers planned together', 'Coordinated with false ceiling design', 'Scene-based control where automated', 'Fixtures chosen to match the room\'s material language'],
    gallery: [
      ai('FALSE CIELING DESIGN/fc6.webp', 'Ambient lighting concept, Jaipur'),
      ai('FALSE CIELING DESIGN/fc1.webp', 'Ceiling lighting concept, Jaipur'),
      real('TV UNIT DESIGN/Vizora House G.F. A01_View020000.webp', 'TV unit with integrated lighting, Vizora House, Jaipur'),
      ai('TV UNIT DESIGN/tv5.webp', 'Media wall lighting concept, Jaipur'),
    ],
    gallerySlug: 'living-room',
    serviceSlug: 'home-automation',
    relatedPortfolioSlugs: ['vizora-house', 'krish-ji-residence'],
  },
  {
    slug: 'ceilings',
    title: 'Ceilings',
    eyebrow: 'Interior Element',
    heroImage: ai('FALSE CIELING DESIGN/fc1.webp', 'False ceiling design concept, Jaipur'),
    description: 'False ceilings planned alongside lighting and HVAC — not a decorative layer added last, but part of the room\'s structural and lighting plan from the start.',
    highlights: ['Coordinated with lighting and HVAC layout', 'Cove and panel detailing to match room proportions', 'Acoustic treatment where needed', 'Finished in the same palette as the walls'],
    gallery: [
      ai('FALSE CIELING DESIGN/fc3.webp', 'False ceiling concept, Jaipur'),
      ai('FALSE CIELING DESIGN/fc7.webp', 'False ceiling concept, Jaipur'),
      real('FALSE CEILINGS DESIGN/Rishabh ji  final 20-5-2025 A01_View010078.webp', 'False ceiling, Rishabh Residence, Jaipur'),
      ai('FALSE CIELING DESIGN/fc8.webp', 'False ceiling concept, Jaipur'),
    ],
    gallerySlug: 'living-room',
    serviceSlug: 'home-automation',
    relatedPortfolioSlugs: ['rishabh-ji-residence', 'vizora-house'],
  },
  {
    slug: 'wall-finishes',
    title: 'Wall Finishes',
    eyebrow: 'Interior Element',
    heroImage: real('FOYER DESIGN/Vizora House G.F. A01_View130000.webp', 'Textured wall finish, Vizora House, Jaipur'),
    description: 'From stone cladding to veneer panelling — wall finishes chosen to anchor a room\'s material story, most often at the one feature wall that sets the tone for everything else.',
    highlights: ['Stone, veneer and textured plaster options', 'Feature walls planned as the room\'s anchor', 'Durable finishes for high-traffic areas', 'Matched to flooring and ceiling materials'],
    gallery: [
      real('FOYER DESIGN/Rakesh ji Maheshwari A01.webp', 'Feature wall, Rakesh Residence, Jaipur'),
      real('LIVING ROOM DESIGN/Krish ji S.F. A01_View140000.webp', 'Living room feature wall, Krish Residence, Jaipur'),
      real('FOYER DESIGN/krish ji entrance+kitchen+dining area A01_View010100 lux.webp', 'Entrance wall finish, Krish Residence, Jaipur'),
      real('FOYER DESIGN/Paritosh ji Living A01_View020000.webp', 'Foyer wall finish, Paritosh Residence, Jaipur'),
    ],
    gallerySlug: 'full-home',
    serviceSlug: 'full-home-interior-design',
    relatedPortfolioSlugs: ['vizora-house', 'rakesh-ji-residence'],
  },
  {
    slug: 'flooring',
    title: 'Flooring',
    eyebrow: 'Interior Element',
    heroImage: real('LIVING ROOM DESIGN/Vizora House G.F. A01_View010000.webp', 'Marble flooring, Vizora House, Jaipur'),
    description: 'Flooring chosen to carry one visual language from the foyer through to the living areas, balancing durability with the room\'s overall material story.',
    highlights: ['Marble, wood and tile options matched to use', 'One flooring language carried room to room', 'Durability matched to foot traffic', 'Coordinated with skirting and wall finishes'],
    gallery: [
      real('FOYER DESIGN/Vizora House G.F. A01_View130000.webp', 'Foyer flooring, Vizora House, Jaipur'),
      real('LIVING ROOM DESIGN/Rakesh ji living A01_View010000.webp', 'Living room flooring, Rakesh Residence, Jaipur'),
      real('DINING ROOM DESIGN/Karamveer ji G.F. A01_View100000.webp', 'Dining area flooring, Karamveer Residence, Jaipur'),
      real('LIVING ROOM DESIGN/Paritosh ji Living A01_View050000.webp', 'Living room flooring, Paritosh Residence, Jaipur'),
    ],
    gallerySlug: 'full-home',
    serviceSlug: 'full-home-interior-design',
    relatedPortfolioSlugs: ['vizora-house', 'karamveer-ji-residence'],
  },
  {
    slug: 'doors',
    title: 'Doors',
    eyebrow: 'Interior Element',
    heroImage: real('FOYER DESIGN/krish ji entrance+kitchen+dining area A01_View020100 lux.webp', 'Entrance door design, Krish Residence, Jaipur'),
    description: 'From the main entrance to internal room doors and wardrobe shutters — designed as part of the wall they sit in, not a fitted, off-the-shelf afterthought.',
    highlights: ['Entrance doors designed as a design statement', 'Internal doors matched to room finishes', 'Soft-close and premium hardware throughout', 'Wardrobe and cabinet shutters included'],
    gallery: [
      real('FOYER DESIGN/Rakesh ji living C01_View050000.webp', 'Entrance detail, Rakesh Residence, Jaipur'),
      real('WARDROBE DESIGN/Krish ji Dressing A01_View020000.webp', 'Wardrobe door detail, Krish Residence, Jaipur'),
      real('FOYER DESIGN/Paritosh ji Living A01_View010000.webp', 'Entrance foyer, Paritosh Residence, Jaipur'),
      real('WARDROBE DESIGN/GAUTMA JI M. BEDROOM DRESSING A02.webp', 'Wardrobe shutter detail, Jaipur'),
    ],
    gallerySlug: 'full-home',
    serviceSlug: 'full-home-interior-design',
    relatedPortfolioSlugs: ['krish-ji-residence', 'rakesh-ji-residence'],
  },
  {
    slug: 'windows',
    title: 'Windows',
    eyebrow: 'Interior Element',
    heroImage: real('BALCONY DESIGN/Mohit ji Bathroom and balcony A01_View020000.webp', 'Window and balcony design, Jaipur'),
    description: 'Window treatments and glazing planned together with the balcony and curtain design, so natural light is shaped rather than simply let in.',
    highlights: ['Curtain and blind design coordinated with windows', 'Natural light planned into the room layout', 'Balcony and window sightlines treated as one', 'Motorised options where automated'],
    gallery: [
      real('BALCONY DESIGN/Krish ji S.F. Bathrooms A01_View160042.webp', 'Balcony and window, Krish Residence, Jaipur'),
      real('BALCONY DESIGN/Rakesh ji Dressings_View030000.webp', 'Window detail, Rakesh Residence, Jaipur'),
      real('BALCONY DESIGN/Ved Prakash Daughter room Balcony A_View010000.webp', 'Balcony window, Ved Prakash Residence, Jaipur'),
      real('LIVING ROOM DESIGN/Vizora House G.F. A01_View020000.webp', 'Living room windows, Vizora House, Jaipur'),
    ],
    gallerySlug: 'living-room',
    serviceSlug: 'home-automation',
    relatedPortfolioSlugs: ['vizora-house', 'ved-prakash-residence'],
  },
  {
    slug: 'kids-room',
    title: 'Kids Room',
    eyebrow: 'Interior Element',
    heroImage: real('KIDS BEDROOM DESIGN/Krish ji f.f. Kids bedroom A01.webp', "Kids' bedroom by Luxora, Jaipur"),
    description: 'Playful without being disposable — durable materials and flexible layouts that can grow with a child from nursery to teenage years.',
    highlights: ['Durable, easy-to-clean surface materials', 'Flexible study and storage zones', 'Safe, rounded detailing throughout', 'Designed to adapt as children grow'],
    gallery: [
      real('KIDS BEDROOM DESIGN/Ved Prakash Daughter room A_View010000.webp', "Daughter's bedroom, Ved Prakash Residence, Jaipur"),
      real('KIDS BEDROOM DESIGN/Rishabh ji final render 07.webp', "Daughter's bedroom, Rishabh Residence, Jaipur"),
      real('KIDS BEDROOM DESIGN/Krish ji Girls bedroom A01.webp', "Kids' bedroom, Krish Residence, Jaipur"),
      real('KIDS BEDROOM DESIGN/Krish ji f.f. Kids bedroom A02.webp', "Kids' bedroom detail, Krish Residence, Jaipur"),
    ],
    gallerySlug: 'bedroom',
    serviceSlug: 'bedroom-interior-design',
    relatedPortfolioSlugs: ['krish-ji-residence', 'rishabh-ji-residence', 'ved-prakash-residence'],
  },
  {
    slug: 'balcony',
    title: 'Balcony',
    eyebrow: 'Interior Element',
    heroImage: real('BALCONY DESIGN/Mohit ji Bathroom and balcony A01_View010000.webp', 'Balcony design by Luxora, Jaipur'),
    description: 'Treated as a genuine extension of the room it opens from — finished with the same flooring and detailing carried through from inside, not left as leftover outdoor space.',
    highlights: ['Flooring and railing matched to the adjoining room', 'Seating and greenery planned into the layout', 'Weather-resistant finishes and fittings', 'Coordinated with window and curtain design'],
    gallery: [
      real('BALCONY DESIGN/Rakesh ji Dressings_View040000.webp', 'Balcony, Rakesh Residence, Jaipur'),
      real('BALCONY DESIGN/Ved Prakash Daughter room Balcony A_View010000.webp', 'Balcony, Ved Prakash Residence, Jaipur'),
      real('BALCONY DESIGN/Krish ji S.F. Bathrooms A01_View170042.webp', 'Balcony, Krish Residence, Jaipur'),
      real('BALCONY DESIGN/Saurabh jain f.f. B01_View180100.webp', 'Balcony, Saurabh Jain Residence, Jaipur'),
    ],
    gallerySlug: 'living-room',
    serviceSlug: 'full-home-interior-design',
    relatedPortfolioSlugs: ['mohit-ji-residence', 'rakesh-ji-residence', 'ved-prakash-residence'],
  },
  {
    slug: 'hardware',
    title: 'Hardware',
    eyebrow: 'Interior Element',
    heroImage: real('WARDROBE DESIGN/Rishabh ji final render B04.webp', 'Wardrobe hardware detail, Jaipur'),
    description: 'The detail that decides how a space feels after a year of daily use — German-grade hinges, channels and handles fitted as standard across every cabinet and door.',
    highlights: ['German-grade soft-close hinges and channels', 'Handles and pulls matched to the room\'s finish', 'Motion-sensor lighting hardware where used', 'Fitted and tested on-site before handover'],
    gallery: [
      real('MODULAR KITCHEN/Krish ji D01_View010000.webp', 'Kitchen hardware detail, Krish Residence, Jaipur'),
      real('WARDROBE DESIGN/Krish ji Dressing A01_View030000.webp', 'Wardrobe hardware, Krish Residence, Jaipur'),
      real('WARDROBE DESIGN/Rishabh ji Doughter bedroom dressing A02.webp', 'Dressing hardware detail, Jaipur'),
      real('MODULAR KITCHEN/Rishabh ji kitchen E02.webp', 'Kitchen hardware, Rishabh Residence, Jaipur'),
    ],
    gallerySlug: 'kitchen',
    serviceSlug: 'modular-kitchen-design',
    relatedPortfolioSlugs: ['krish-ji-residence', 'rishabh-ji-residence'],
  },
];
